import 'package:cloud_firestore/cloud_firestore.dart';

/// Avatar mẫu trên Firebase Storage (chỉ dùng seed debug).
abstract final class StudentSeedAvatars {
  static const boy =
      'https://firebasestorage.googleapis.com/v0/b/tanlu-ceab0.firebasestorage.app/o/avartar-boy.png?alt=media&token=879c8ab2-ebcc-4c0e-bf2f-8fdd55214ddf';
  static const girl =
      'https://firebasestorage.googleapis.com/v0/b/tanlu-ceab0.firebasestorage.app/o/avartar-girl.png?alt=media&token=279b3523-c712-45c0-91b2-ecf8622fcb6e';
}

class _SeedStudent {
  const _SeedStudent({
    required this.id,
    required this.classId,
    required this.classNum,
    required this.index,
    required this.fullName,
    required this.nickname,
    required this.gender,
    required this.dob,
    required this.fatherName,
    required this.motherName,
    required this.fatherPhone,
    required this.motherPhone,
    required this.fatherDob,
    required this.motherDob,
    required this.address,
    this.diagnosis = '',
    this.allergies = '',
    this.developmentAgeMonth = 24,
  });

  final String id;
  final String classId;
  final int classNum;
  final int index;
  final String fullName;
  final String nickname;
  final String gender;
  final String dob;
  final String fatherName;
  final String motherName;
  final String fatherPhone;
  final String motherPhone;
  final String fatherDob;
  final String motherDob;
  final String address;
  final String diagnosis;
  final String allergies;
  final int developmentAgeMonth;

  String get studentCode => 'HS-C$classNum-${index.toString().padLeft(3, '0')}';

  String get avatarUrl =>
      gender == 'Nam' ? StudentSeedAvatars.boy : StudentSeedAvatars.girl;

  Map<String, dynamic> toFirestore() {
    return {
      'classId': classId,
      'fullName': fullName,
      'nickname': nickname,
      'gender': gender,
      'dob': dob,
      'dateOfBirth': dob,
      'avatarUrl': avatarUrl,
      'studentCode': studentCode,
      'status': 'active',
      'address': address,
      'birthHistory': '',
      'bloodType': '',
      'diagnosis': diagnosis,
      'allergies': allergies,
      'currentMedications': '',
      'likes': '',
      'dislikesOrTriggers': '',
      'selfCareSkills': '',
      'initialReason': '',
      'diagnosisSummary': diagnosis,
      'developmentAgeMonth': developmentAgeMonth,
      'supportLevel': '',
      'parentUserId': '',
      'contacts': [
        {
          'name': fatherName,
          'relationship': 'Bố',
          'phone': fatherPhone,
          'dob': fatherDob,
          'isPrimary': true,
        },
        {
          'name': motherName,
          'relationship': 'Mẹ',
          'phone': motherPhone,
          'dob': motherDob,
          'isPrimary': false,
        },
      ],
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
    };
  }
}

const _class1Students = [
  _SeedStudent(
    id: 'student-c1-001',
    classId: 'class-1',
    classNum: 1,
    index: 1,
    fullName: 'An Bình',
    nickname: 'Bình',
    gender: 'Nam',
    dob: '2022-04-12',
    fatherName: 'Nguyễn Văn Tuấn',
    motherName: 'Trần Thị Hương',
    fatherPhone: '0912345601',
    motherPhone: '0987654301',
    fatherDob: '1990-01-01',
    motherDob: '1992-05-10',
    address: 'Quận 1, TP.Hồ Chí Minh',
    diagnosis: 'Rối loạn phổ tự kỷ (Nhẹ)',
    allergies: 'Hải sản, Đậu phộng',
    developmentAgeMonth: 24,
  ),
  _SeedStudent(
    id: 'student-c1-002',
    classId: 'class-1',
    classNum: 1,
    index: 2,
    fullName: 'Minh Châu',
    nickname: 'Châu',
    gender: 'Nữ',
    dob: '2022-07-08',
    fatherName: 'Lê Hoàng Nam',
    motherName: 'Phạm Thị Mai',
    fatherPhone: '0912345602',
    motherPhone: '0987654302',
    fatherDob: '1989-03-15',
    motherDob: '1991-08-22',
    address: 'Quận 3, TP.Hồ Chí Minh',
    developmentAgeMonth: 22,
  ),
  _SeedStudent(
    id: 'student-c1-003',
    classId: 'class-1',
    classNum: 1,
    index: 3,
    fullName: 'Gia Huy',
    nickname: 'Huy',
    gender: 'Nam',
    dob: '2021-11-20',
    fatherName: 'Trần Quốc Bảo',
    motherName: 'Nguyễn Thị Lan',
    fatherPhone: '0912345603',
    motherPhone: '0987654303',
    fatherDob: '1988-06-30',
    motherDob: '1990-12-05',
    address: 'Quận Bình Thạnh, TP.Hồ Chí Minh',
    diagnosis: 'Chậm nói',
    developmentAgeMonth: 28,
  ),
  _SeedStudent(
    id: 'student-c1-004',
    classId: 'class-1',
    classNum: 1,
    index: 4,
    fullName: 'Diệu Linh',
    nickname: 'Linh',
    gender: 'Nữ',
    dob: '2022-01-14',
    fatherName: 'Hoàng Văn Đức',
    motherName: 'Võ Thị Ngọc',
    fatherPhone: '0912345604',
    motherPhone: '0987654304',
    fatherDob: '1991-02-18',
    motherDob: '1993-07-09',
    address: 'Quận Phú Nhuận, TP.Hồ Chí Minh',
    developmentAgeMonth: 26,
  ),
  _SeedStudent(
    id: 'student-c1-005',
    classId: 'class-1',
    classNum: 1,
    index: 5,
    fullName: 'Quốc Anh',
    nickname: 'Anh',
    gender: 'Nam',
    dob: '2022-09-03',
    fatherName: 'Phạm Minh Khang',
    motherName: 'Lê Thị Hà',
    fatherPhone: '0912345605',
    motherPhone: '0987654305',
    fatherDob: '1990-09-25',
    motherDob: '1992-11-11',
    address: 'Quận 7, TP.Hồ Chí Minh',
    allergies: 'Sữa bò',
    developmentAgeMonth: 20,
  ),
  _SeedStudent(
    id: 'student-c1-006',
    classId: 'class-1',
    classNum: 1,
    index: 6,
    fullName: 'Lê Thảo Vy',
    nickname: 'Vy',
    gender: 'Nữ',
    dob: '2021-12-28',
    fatherName: 'Nguyễn Đình Phong',
    motherName: 'Trương Thị Uyên',
    fatherPhone: '0912345606',
    motherPhone: '0987654306',
    fatherDob: '1989-04-04',
    motherDob: '1991-10-20',
    address: 'Quận Tân Bình, TP.Hồ Chí Minh',
    diagnosis: 'Rối loạn phổ tự kỷ (Nhẹ)',
    developmentAgeMonth: 30,
  ),
  _SeedStudent(
    id: 'student-c1-007',
    classId: 'class-1',
    classNum: 1,
    index: 7,
    fullName: 'Bảo Nam',
    nickname: 'Nam',
    gender: 'Nam',
    dob: '2022-05-17',
    fatherName: 'Đỗ Văn Hải',
    motherName: 'Bùi Thị Chi',
    fatherPhone: '0912345607',
    motherPhone: '0987654307',
    fatherDob: '1992-01-08',
    motherDob: '1994-06-16',
    address: 'Quận Gò Vấp, TP.Hồ Chí Minh',
    developmentAgeMonth: 23,
  ),
  _SeedStudent(
    id: 'student-c1-008',
    classId: 'class-1',
    classNum: 1,
    index: 8,
    fullName: 'Ngọc Hân',
    nickname: 'Hân',
    gender: 'Nữ',
    dob: '2022-02-22',
    fatherName: 'Vũ Quang Huy',
    motherName: 'Đặng Thị Linh',
    fatherPhone: '0912345608',
    motherPhone: '0987654308',
    fatherDob: '1990-07-07',
    motherDob: '1992-03-03',
    address: 'Quận 10, TP.Hồ Chí Minh',
    allergies: 'Trứng',
    developmentAgeMonth: 25,
  ),
  _SeedStudent(
    id: 'student-c1-009',
    classId: 'class-1',
    classNum: 1,
    index: 9,
    fullName: 'Đăng Khoa',
    nickname: 'Khoa',
    gender: 'Nam',
    dob: '2021-10-05',
    fatherName: 'Lý Văn Tài',
    motherName: 'Hồ Thị Yến',
    fatherPhone: '0912345609',
    motherPhone: '0987654309',
    fatherDob: '1988-11-19',
    motherDob: '1990-05-28',
    address: 'Quận 2, TP.Hồ Chí Minh',
    developmentAgeMonth: 32,
  ),
  _SeedStudent(
    id: 'student-c1-010',
    classId: 'class-1',
    classNum: 1,
    index: 10,
    fullName: 'Kim Ngân',
    nickname: 'Ngân',
    gender: 'Nữ',
    dob: '2022-06-30',
    fatherName: 'Cao Văn Long',
    motherName: 'Dương Thị Nga',
    fatherPhone: '0912345610',
    motherPhone: '0987654310',
    fatherDob: '1991-12-12',
    motherDob: '1993-04-01',
    address: 'Quận Thủ Đức, TP.Hồ Chí Minh',
    developmentAgeMonth: 21,
  ),
];

const _class2Students = [
  _SeedStudent(
    id: 'student-c2-001',
    classId: 'class-2',
    classNum: 2,
    index: 1,
    fullName: 'Tuấn Kiệt',
    nickname: 'Kiệt',
    gender: 'Nam',
    dob: '2022-03-19',
    fatherName: 'Mai Văn Thắng',
    motherName: 'Lương Thị Hạnh',
    fatherPhone: '0922345601',
    motherPhone: '0977654301',
    fatherDob: '1989-08-08',
    motherDob: '1991-01-14',
    address: 'Quận 1, TP.Hồ Chí Minh',
    diagnosis: 'Tăng động giảm chú ý (Nhẹ)',
    developmentAgeMonth: 24,
  ),
  _SeedStudent(
    id: 'student-c2-002',
    classId: 'class-2',
    classNum: 2,
    index: 2,
    fullName: 'Phương Anh',
    nickname: 'Anh',
    gender: 'Nữ',
    dob: '2022-08-11',
    fatherName: 'Ngô Quốc Hùng',
    motherName: 'Tạ Thị Bích',
    fatherPhone: '0922345602',
    motherPhone: '0977654302',
    fatherDob: '1990-02-27',
    motherDob: '1992-09-06',
    address: 'Quận 4, TP.Hồ Chí Minh',
    developmentAgeMonth: 22,
  ),
  _SeedStudent(
    id: 'student-c2-003',
    classId: 'class-2',
    classNum: 2,
    index: 3,
    fullName: 'Hữu Nghĩa',
    nickname: 'Nghĩa',
    gender: 'Nam',
    dob: '2021-09-25',
    fatherName: 'Bùi Văn Sơn',
    motherName: 'Châu Thị Loan',
    fatherPhone: '0922345603',
    motherPhone: '0977654303',
    fatherDob: '1988-05-05',
    motherDob: '1990-10-10',
    address: 'Quận 5, TP.Hồ Chí Minh',
    allergies: 'Đậu phộng',
    developmentAgeMonth: 31,
  ),
  _SeedStudent(
    id: 'student-c2-004',
    classId: 'class-2',
    classNum: 2,
    index: 4,
    fullName: 'Mỹ Duyên',
    nickname: 'Duyên',
    gender: 'Nữ',
    dob: '2022-04-02',
    fatherName: 'Trịnh Văn Phú',
    motherName: 'Huỳnh Thị Trang',
    fatherPhone: '0922345604',
    motherPhone: '0977654304',
    fatherDob: '1991-06-21',
    motherDob: '1993-02-14',
    address: 'Quận 6, TP.Hồ Chí Minh',
    developmentAgeMonth: 25,
  ),
  _SeedStudent(
    id: 'student-c2-005',
    classId: 'class-2',
    classNum: 2,
    index: 5,
    fullName: 'Trung Hiếu',
    nickname: 'Hiếu',
    gender: 'Nam',
    dob: '2022-11-07',
    fatherName: 'Đinh Quang Minh',
    motherName: 'Phan Thị Thu',
    fatherPhone: '0922345605',
    motherPhone: '0977654305',
    fatherDob: '1992-03-30',
    motherDob: '1994-08-18',
    address: 'Quận 8, TP.Hồ Chí Minh',
    developmentAgeMonth: 19,
  ),
  _SeedStudent(
    id: 'student-c2-006',
    classId: 'class-2',
    classNum: 2,
    index: 6,
    fullName: 'Lan Anh',
    nickname: 'Lan',
    gender: 'Nữ',
    dob: '2022-01-30',
    fatherName: 'Võ Đình Khánh',
    motherName: 'Nguyễn Thị Phượng',
    fatherPhone: '0922345606',
    motherPhone: '0977654306',
    fatherDob: '1989-10-02',
    motherDob: '1991-12-25',
    address: 'Quận 11, TP.Hồ Chí Minh',
    diagnosis: 'Chậm phát triển ngôn ngữ',
    developmentAgeMonth: 27,
  ),
  _SeedStudent(
    id: 'student-c2-007',
    classId: 'class-2',
    classNum: 2,
    index: 7,
    fullName: 'Việt Hoàng',
    nickname: 'Hoàng',
    gender: 'Nam',
    dob: '2021-12-15',
    fatherName: 'Lê Văn Cường',
    motherName: 'Trần Thị Oanh',
    fatherPhone: '0922345607',
    motherPhone: '0977654307',
    fatherDob: '1990-04-17',
    motherDob: '1992-07-23',
    address: 'Quận Bình Tân, TP.Hồ Chí Minh',
    developmentAgeMonth: 29,
  ),
  _SeedStudent(
    id: 'student-c2-008',
    classId: 'class-2',
    classNum: 2,
    index: 8,
    fullName: 'Thu Hà',
    nickname: 'Hà',
    gender: 'Nữ',
    dob: '2022-05-26',
    fatherName: 'Phạm Xuân Thành',
    motherName: 'Đỗ Thị Quỳnh',
    fatherPhone: '0922345608',
    motherPhone: '0977654308',
    fatherDob: '1991-09-09',
    motherDob: '1993-03-12',
    address: 'Quận Tân Phú, TP.Hồ Chí Minh',
    allergies: 'Hải sản',
    developmentAgeMonth: 23,
  ),
  _SeedStudent(
    id: 'student-c2-009',
    classId: 'class-2',
    classNum: 2,
    index: 9,
    fullName: 'Minh Đức',
    nickname: 'Đức',
    gender: 'Nam',
    dob: '2022-07-21',
    fatherName: 'Hoàng Văn Lộc',
    motherName: 'Lý Thị Giang',
    fatherPhone: '0922345609',
    motherPhone: '0977654309',
    fatherDob: '1992-11-03',
    motherDob: '1994-05-19',
    address: 'Quận 12, TP.Hồ Chí Minh',
    developmentAgeMonth: 22,
  ),
  _SeedStudent(
    id: 'student-c2-010',
    classId: 'class-2',
    classNum: 2,
    index: 10,
    fullName: 'Bích Ngọc',
    nickname: 'Ngọc',
    gender: 'Nữ',
    dob: '2022-10-09',
    fatherName: 'Nguyễn Hữu Tâm',
    motherName: 'Vương Thị Hiền',
    fatherPhone: '0922345610',
    motherPhone: '0977654310',
    fatherDob: '1990-12-01',
    motherDob: '1992-06-06',
    address: 'Quận Nhà Bè, TP.Hồ Chí Minh',
    developmentAgeMonth: 20,
  ),
];

/// Ghi 20 học sinh demo (10 × class-1, 10 × class-2) lên Firestore.
Future<void> seedDemoStudentsToFirestore() async {
  final firestore = FirebaseFirestore.instance;
  final batch = firestore.batch();
  final all = [..._class1Students, ..._class2Students];

  for (final student in all) {
    batch.set(
      firestore.collection('students').doc(student.id),
      student.toFirestore(),
    );
  }

  await batch.commit();
}

int get demoStudentSeedCount => _class1Students.length + _class2Students.length;
